# Generated by Django 5.1 on 2024-08-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_csvdata_data_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_csv',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
