# Generated by Django 5.1 on 2024-08-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_data_csv_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('course', models.FloatField()),
                ('speed_kts', models.FloatField()),
                ('speed_mph', models.FloatField()),
                ('altitude_feet', models.FloatField()),
                ('reporting_facility', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='data_csv',
        ),
    ]
