# Generated by Django 5.1 on 2024-08-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_csvdata_delete_data_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='time',
            field=models.TimeField(),
        ),
    ]
