# Generated by Django 5.1 on 2024-08-18 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=(0.0, 0.0), max_length=100),
            preserve_default=False,
        ),
    ]
