# Generated by Django 5.1 on 2024-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='point',
            field=models.JSONField(default=(0.0, 0.0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
