# Generated by Django 5.1 on 2024-08-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_location_coordinates_location_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='point',
            new_name='Point',
        ),
    ]
