# Generated by Django 5.1 on 2024-08-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Point',
            new_name='point',
        ),
    ]
