# Generated by Django 5.1 on 2024-08-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_name_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
