# Generated by Django 5.1 on 2024-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='point',
            field=models.BinaryField(),
        ),
    ]
