# Generated by Django 5.1 on 2024-08-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_location_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
        migrations.AddField(
            model_name='location',
            name='point_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='point_wkb',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
