# Generated by Django 5.1 on 2024-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_location_point_location_point_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='point_json',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_wkb',
        ),
        migrations.AddField(
            model_name='location',
            name='point',
            field=models.BinaryField(default=b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
        ),
    ]
