# Generated by Django 5.1 on 2024-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_location_point_json_remove_location_point_wkb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='point',
            field=models.BinaryField(),
        ),
    ]
