# Generated by Django 5.1 on 2024-08-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_location_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='GeospatialPoint',
        ),
    ]
