# Generated by Django 5.1 on 2024-08-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_location_geospatialpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialpoint',
            name='name',
        ),
    ]
