# Generated by Django 5.1 on 2024-08-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_geospatialpoint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialpoint',
            name='point',
            field=models.CharField(max_length=100),
        ),
    ]
