# Generated by Django 5.1 on 2024-08-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_geospatialpoint_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialpoint',
            name='point',
        ),
        migrations.AddField(
            model_name='geospatialpoint',
            name='wkb_hex',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
